### ISSUE TITLE
My API is not Work like your API

### ISSUE THREAD

**Issue by dante1989** [tosunthex/CoinMarketCapPro-API#4]
_coinMarketCapClient = new CoinMarketCapClient(new HttpClientHandler(), ApiEnvironment.Sandbox, "5bb4185b-ebb3-4cf7-942a-66a280f5db8b");

I see your code and your API in testing project
I Run and it works smoothly
but when i replace by my free API: 6a82de46-f427.........
This Pro API is Basic Plan Free 
But i did not work and get error
i tried to email to coinmarketcap, they said that my API is active, no problem
Please help me me why?

**Comment by tosunthex** [comment]
Hi @dante1989 
You are using Pro API key not for sandbox api. For sandbox API KEY you must create account from https://sandbox.coinmarketcap.com/ then use that key. If you want to work with real data you must changed the ApiEnvirinment to Pro

` _coinMarketCapClient = new CoinMarketCapClient(new HttpClientHandler(), ApiEnvironment.Pro,"6a82de46-f427-4c78-890c-efa86a719d67");`

I hope this will help to you

**Comment by dante1989** [comment]
what is diffrent between sandbox and pro. Should i use sandbox or pro for stableling?

**Comment by tosunthex** [comment]
@dante1989 sandbox services gives you dummy data and you can use all services without any limit but if you want to work with real data Pro services have some call limit (you can check your credit from dashboard) and you must checked the documentation for which services you can use.

For example you cant use Get market pairs (latest) with Basic plan 
[https://pro.coinmarketcap.com/api/v1#operation/getV1CryptocurrencyListingsLatest](url)

For Pro API Limitation
[https://pro.coinmarketcap.com/features](url)

**Comment by dante1989** [comment]
really thank you for helping carefully
I have a top website relating crytocurrency in Vietnam: [https://trungvanhoang.com/](url)
If you want me to help, i will review and introduce your API Code to my audience for thanking you

**Comment by bobbyong** [comment]
Hi @dante1989 do you want to consider using CoinGecko's free API here which is comprehensive with most token info and used by many big crypto websites too? You can take a look here: https://www.coingecko.com/api

Happy to be of assistance if you have any questions

**Comment by tosunthex** [comment]
@dante1989 i will be happy if you do that : )

@bobbyong  I like your site and you're actually doing good job if i have enough time i will make a nuget package for your site too.

**Comment by bobbyong** [comment]
@tosunthex that is great to hear! Do let us know if you make a nuget package and inform us at hello@coingecko.com we would love to take a look. Thank you :)

**Comment by dante1989** [comment]
@bobbyong i will test after having nuget package. Thank you :D

**Comment by tosunthex** [comment]
@bobbyong @dante1989 
Hi I just published coin gecko nuget package and you can find it in the [nuget CoinGeckoAsyncApi](https://www.nuget.org/packages/CoinGeckoAsyncApi/) 

If I miss some thing or made a mistake please [open Issue](https://github.com/tosunthex/CoinGecko/issues)

If you can give me some feedback i will be very happy.  Merry Chrismas.
